"""Report Agent - generates HTML risk reports."""
from typing import List

from models.schemas import RiskFinding


class ReportAgent:
    def generate(
        self,
        contract_name: str,
        findings: List[RiskFinding],
        compliance_issues: List[str],
        output_path: str,
    ) -> None:
        high = sum(1 for f in findings if f.risk_level == "HIGH")
        med = sum(1 for f in findings if f.risk_level == "MEDIUM")
        low = sum(1 for f in findings if f.risk_level == "LOW")

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Risk Report - {contract_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; background: #f8f9fa; }}
        h1 {{ color: #1a1a2e; border-bottom: 3px solid #00b4d8; padding-bottom: 10px; }}
        .summary {{ background: white; padding: 20px; border-radius: 10px; margin: 20px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
        .finding {{ background: white; padding: 15px; margin: 10px 0; border-radius: 8px; border-left: 5px solid #ccc; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
        .finding.HIGH {{ border-left-color: #e63946; }}
        .finding.MEDIUM {{ border-left-color: #f4a261; }}
        .finding.LOW {{ border-left-color: #2a9d8f; }}
        .badge {{ display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; color: white; }}
        .badge.HIGH {{ background: #e63946; }}
        .badge.MEDIUM {{ background: #f4a261; }}
        .badge.LOW {{ background: #2a9d8f; }}
        .step {{ font-size: 13px; color: #555; margin: 5px 0; padding: 5px; background: #f1f3f5; border-radius: 4px; }}
    </style>
</head>
<body>
    <h1>Risk Report for: {contract_name}</h1>
    <div class="summary">
        <h2>Summary</h2>
        <p><span class="badge HIGH">{high} HIGH</span> <span class="badge MEDIUM">{med} MEDIUM</span> <span class="badge LOW">{low} LOW</span></p>
        <p>Generated by Legal Contract Review Agent (Multi-Agent System)</p>
    </div>
    <h2>Risk Findings</h2>
"""

        for f in findings:
            html += f"""
    <div class="finding {f.risk_level}">
        <strong>Clause [{f.clause_id}]</strong>
        <span class="badge {f.risk_level}">{f.risk_level}</span>
        <span>Score: {f.score}</span>
        <p><strong>Suggestion:</strong> {f.suggestion}</p>
        <details>
            <summary>Reasoning Steps ({len(f.reasoning_steps)} steps)</summary>
"""
            for step in f.reasoning_steps:
                status = "✅" if step.passed else "❌"
                html += f'            <div class="step">{status} [{step.regulation}] {step.check}<br/><em>{step.explanation}</em></div>\n'
            html += "        </details>\n    </div>\n"

        if compliance_issues:
            html += "    <h2>Compliance Issues</h2>\n    <ul>\n"
            for issue in compliance_issues:
                html += f"        <li>{issue}</li>\n"
            html += "    </ul>\n"

        html += """</body>\n</html>"""

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
